name: String extraction test
on:
  pull_request:
jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Install Linux packages
        run: |
          sudo apt update
          sudo apt install gettext -y
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install global npm packages
        run: |
          npm install -g grunt-cli
      - name: Clone l10n repository
        uses: actions/checkout@v3
        with:
          repository: mozilla/fxa-content-server-l10n
          path: "fxa-l10n"
      - name: Clone FxA code repository
        uses: actions/checkout@v3
        with:
          repository: "bcolsson/fxa"
          fetch-depth: 1
          path: "fxa-code"
      - name: Install npm packages
        run: |
          cd fxa-l10n
          npm install
      - name: Extract strings
        run: |
          cd fxa-code
          yarn workspaces focus fxa-content-server fxa-auth-server fxa-payments-server fxa-settings
          yarn workspace fxa-settings build
          yarn workspace fxa-auth-server grunt merge-ftl

          NODE_ENV=development ../fxa-l10n/scripts/extract_strings.sh \
            --mailer-repo ./packages/fxa-auth-server \
            --payments-repo ./packages/fxa-payments-server \
            --content-repo ./packages/fxa-content-server \
            --settings-repo ./packages/fxa-settings \
            --l10n-repo ../fxa-l10n
      - name: Commit changes and open pull request
        run: |
          # Only try to commit if there are pending changes
          cd fxa-l10n
          if [[ $(git diff --exit-code) || $(git ls-files --other --exclude-standard) ]]
            # Add mozilla/fxa-l10n as reviewer for pull request if .po file changes
            gh pr edit --add-reviewer mozilla/fxa-l10n
          else
            echo "No changes found."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.FXA_GITHUB_TOKEN }}
